### ISSUE TITLE
You are supposed to remove this line. This is a pick error.

### ISSUE THREAD

**Issue by GuaiYiHu** [Fabulous-Oreo/kernel_oneplus_msm8974#2]
https://github.com/Fabulous-Oreo/kernel_oneplus_msm8974/blob/f2e955175cc3b3e3eb7b34085fb06b43a70ebe11/fs/fs_struct.c#L130

See this before:
https://github.com/Fabulous-Oreo/kernel_oneplus_msm8974/commit/79943f8a757740caed347c0697b14bab343ba6a7#diff-3f36df752f42f36e2628598141e0268c

**Comment by AgentFabulous** [comment]
Thanks, I'll fix this :)
